# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vzomber <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/02 15:47:52 by vzomber           #+#    #+#              #
#    Updated: 2017/11/03 17:55:42 by vzomber          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file 

SRC = ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
